# Análise exploratória dos dados

## Importando as bibliotecas

In [2598]:
import pandas as pd
import numpy as np
import ast
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

## Caminho para o dataset

In [2599]:
path_csv = '../data/raw/movies_dataset.csv'

## Lendo o dataset

In [2600]:
df = pd.read_csv(path_csv, sep=',')
df

,id,title,original_title,original_language,overview,tagline,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count
0,411405,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",NaN,0.0,0.0,95.0,2017-04-28,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",7.219022,5.8,55.0
1,42492,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",NaN,0.0,0.0,97.0,1972-12-21,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",0.138450,7.3,2.0
2,12143,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",Gambler. Thief. Junkie. Killer. Cop.,1000000.0,2019469.0,96.0,1992-09-16,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",6.417037,6.9,162.0
3,9976,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,You'll laugh 'til you die,0.0,0.0,100.0,2004-01-01,"[{'id': 27, 'name': 'Horror'}, {'id': 10749, '...",2.233189,5.0,42.0
4,46761,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,NaN,0.0,0.0,80.0,1998-05-27,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1.800582,6.4,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4997,9803,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,NaN,0.0,0.0,95.0,2004-10-28,"[{'id': 35, 'name': 'Comedy'}]",4.582736,5.2,70.0
4998,336970,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",NaN,0.0,0.0,58.0,2000-09-13,"[{'id': 18, 'name': 'Drama'}, {'id': 10770, 'n...",2.364355,8.0,2.0
4999,336691,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",NaN,0.0,0.0,90.0,2015-11-24,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",0.448056,7.0,4.0
5000,37598,Butch and Sundance: The Early Days,Butch and Sundance: The Early Days,en,"A ""prequel"" of sorts to ""Butch Cassidy and the...",Before the fame when fun was the name of the g...,0.0,0.0,115.0,1979-06-15,"[{'id': 37, 'name': 'Western'}]",0.627647,4.6,8.0
5001,65766,Bon appétit,Bon appétit,en,A romantic comedy centered on two young cooks ...,NaN,0.0,0.0,91.0,2010-11-12,"[{'id': 10749, 'name': 'Romance'}]",0.965179,5.3,8.0

## Análise exploratória

Inicialmente, pelas informações do dataframe (DF), vemos que o range de índices corresponde ao total de linhas e o DF possui 14 colunas com os tipos: `object`, `float64` e `int64`.

In [2601]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5002 entries, 0 to 5001
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5002 non-null   int64
 1   title              5001 non-null   object
 2   original_title     5002 non-null   object
 3   original_language  5001 non-null   object
 4   overview           4904 non-null   object
 5   tagline            2246 non-null   object
 6   budget             4802 non-null   float64
 7   revenue            4851 non-null   float64
 8   runtime            4875 non-null   object
 9   release_date       4888 non-null   object
 10  genres             5002 non-null   object
 11  popularity         5001 non-null   float64
 12  vote_average       5001 non-null   float64
 13  vote_count         5001 non-null   float64
dtypes: float64(5), int64(1), object(8)
memory usage: 547.2+ KB

Notamos que a coluna `genres` possuem dados que são strings de uma lista de dicionários, logo iremos primeiramente tratar essa coluna.

In [2602]:
df['genres'][3]

"[{'id': 27, 'name': 'Horror'}, {'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]"

Vamos transformar os dados em `genres` para uma lista de dicionários.

In [2603]:
df['genres'] = df['genres'].apply(ast.literal_eval)

Agora transformamos cada linha de `genres` para uma lista de `strings`.

In [2604]:
df['genres'] = df['genres'].apply(lambda genres: [g['name'] for g in genres])

In [2605]:
df

,id,title,original_title,original_language,overview,tagline,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count
0,411405,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",NaN,0.0,0.0,95.0,2017-04-28,"[Drama, Comedy, Thriller, Crime]",7.219022,5.8,55.0
1,42492,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",NaN,0.0,0.0,97.0,1972-12-21,"[Drama, Comedy]",0.138450,7.3,2.0
2,12143,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",Gambler. Thief. Junkie. Killer. Cop.,1000000.0,2019469.0,96.0,1992-09-16,"[Crime, Drama]",6.417037,6.9,162.0
3,9976,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,You'll laugh 'til you die,0.0,0.0,100.0,2004-01-01,"[Horror, Romance, Comedy]",2.233189,5.0,42.0
4,46761,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,NaN,0.0,0.0,80.0,1998-05-27,"[Comedy, Drama, Thriller]",1.800582,6.4,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4997,9803,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,NaN,0.0,0.0,95.0,2004-10-28,[Comedy],4.582736,5.2,70.0
4998,336970,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",NaN,0.0,0.0,58.0,2000-09-13,"[Drama, TV Movie]",2.364355,8.0,2.0
4999,336691,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",NaN,0.0,0.0,90.0,2015-11-24,"[Comedy, Romance]",0.448056,7.0,4.0
5000,37598,Butch and Sundance: The Early Days,Butch and Sundance: The Early Days,en,"A ""prequel"" of sorts to ""Butch Cassidy and the...",Before the fame when fun was the name of the g...,0.0,0.0,115.0,1979-06-15,[Western],0.627647,4.6,8.0
5001,65766,Bon appétit,Bon appétit,en,A romantic comedy centered on two young cooks ...,NaN,0.0,0.0,91.0,2010-11-12,[Romance],0.965179,5.3,8.0

Vamos retirar a coluna de `id`, pois não agrega no DF.

In [2606]:
df.drop(columns=['id'], inplace=True)
df

,title,original_title,original_language,overview,tagline,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count
0,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",NaN,0.0,0.0,95.0,2017-04-28,"[Drama, Comedy, Thriller, Crime]",7.219022,5.8,55.0
1,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",NaN,0.0,0.0,97.0,1972-12-21,"[Drama, Comedy]",0.138450,7.3,2.0
2,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",Gambler. Thief. Junkie. Killer. Cop.,1000000.0,2019469.0,96.0,1992-09-16,"[Crime, Drama]",6.417037,6.9,162.0
3,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,You'll laugh 'til you die,0.0,0.0,100.0,2004-01-01,"[Horror, Romance, Comedy]",2.233189,5.0,42.0
4,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,NaN,0.0,0.0,80.0,1998-05-27,"[Comedy, Drama, Thriller]",1.800582,6.4,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4997,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,NaN,0.0,0.0,95.0,2004-10-28,[Comedy],4.582736,5.2,70.0
4998,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",NaN,0.0,0.0,58.0,2000-09-13,"[Drama, TV Movie]",2.364355,8.0,2.0
4999,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",NaN,0.0,0.0,90.0,2015-11-24,"[Comedy, Romance]",0.448056,7.0,4.0
5000,Butch and Sundance: The Early Days,Butch and Sundance: The Early Days,en,"A ""prequel"" of sorts to ""Butch Cassidy and the...",Before the fame when fun was the name of the g...,0.0,0.0,115.0,1979-06-15,[Western],0.627647,4.6,8.0
5001,Bon appétit,Bon appétit,en,A romantic comedy centered on two young cooks ...,NaN,0.0,0.0,91.0,2010-11-12,[Romance],0.965179,5.3,8.0

## Limpando dados duplicados

Agora vamos retirar os dados duplicados.

Primeiramente, alteraremos as `listas` na coluna `genres` para `tuplas` para não gerar erro na remoção de duplicados.

In [2607]:
df_genres_alterado = df.applymap(lambda x: tuple(x) if isinstance(x, list) else x)
df_genres_alterado

C:\Users\Kleber\AppData\Local\Temp\ipykernel_15444\1575403854.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_genres_alterado = df.applymap(lambda x: tuple(x) if isinstance(x, list) else x)

,title,original_title,original_language,overview,tagline,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count
0,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",NaN,0.0,0.0,95.0,2017-04-28,"(Drama, Comedy, Thriller, Crime)",7.219022,5.8,55.0
1,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",NaN,0.0,0.0,97.0,1972-12-21,"(Drama, Comedy)",0.138450,7.3,2.0
2,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",Gambler. Thief. Junkie. Killer. Cop.,1000000.0,2019469.0,96.0,1992-09-16,"(Crime, Drama)",6.417037,6.9,162.0
3,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,You'll laugh 'til you die,0.0,0.0,100.0,2004-01-01,"(Horror, Romance, Comedy)",2.233189,5.0,42.0
4,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,NaN,0.0,0.0,80.0,1998-05-27,"(Comedy, Drama, Thriller)",1.800582,6.4,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4997,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,NaN,0.0,0.0,95.0,2004-10-28,"(Comedy,)",4.582736,5.2,70.0
4998,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",NaN,0.0,0.0,58.0,2000-09-13,"(Drama, TV Movie)",2.364355,8.0,2.0
4999,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",NaN,0.0,0.0,90.0,2015-11-24,"(Comedy, Romance)",0.448056,7.0,4.0
5000,Butch and Sundance: The Early Days,Butch and Sundance: The Early Days,en,"A ""prequel"" of sorts to ""Butch Cassidy and the...",Before the fame when fun was the name of the g...,0.0,0.0,115.0,1979-06-15,"(Western,)",0.627647,4.6,8.0
5001,Bon appétit,Bon appétit,en,A romantic comedy centered on two young cooks ...,NaN,0.0,0.0,91.0,2010-11-12,"(Romance,)",0.965179,5.3,8.0

In [2608]:
df_genres_alterado.duplicated().sum()

2

Agora, removemos os dados duplicados.

In [2609]:
df_genres_alterado.drop_duplicates(inplace=True)

In [2610]:
df_sem_duplicado = df_genres_alterado.copy()

In [2611]:
df_sem_duplicado.duplicated().sum()

0

# Tratando dados ausentes e mudando tipo de colunas

Verificando os dados ausentes (`NaN`) em cada coluna e tirando a média percebemos que mais de 50% dos dados na coluna `tagline` possuem valores `NaN`. A colouna `tagline` é apenas uma frase promocional curta para divulgar o filme e como é basicamente específica para cada dado podemos retirar essa coluna, pois ela não tem nenhuma ligação com outras colunas, são únicas e não conseguimos atribuir valor para os `NaN`s que são a maior parte dos dados e, assim, não agrega no DF.

In [2612]:
df_sem_duplicado.isnull().sum()

title                   1
original_title          0
original_language       1
overview               98
tagline              2755
budget                200
revenue               151
runtime               127
release_date          114
genres                  0
popularity              1
vote_average            1
vote_count              1
dtype: int64

In [2613]:
df_sem_duplicado.isnull().mean()

title                0.0002
original_title       0.0000
original_language    0.0002
overview             0.0196
tagline              0.5510
budget               0.0400
revenue              0.0302
runtime              0.0254
release_date         0.0228
genres               0.0000
popularity           0.0002
vote_average         0.0002
vote_count           0.0002
dtype: float64

Dropando a coluna `tagline` pois não influencia no DF e tem muito valor ausente (mais de 50%)

In [2614]:
df_sem_duplicado = df_sem_duplicado.drop('tagline', axis=1)
df_sem_duplicado

,title,original_title,original_language,overview,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count
0,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",0.0,0.0,95.0,2017-04-28,"(Drama, Comedy, Thriller, Crime)",7.219022,5.8,55.0
1,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",0.0,0.0,97.0,1972-12-21,"(Drama, Comedy)",0.138450,7.3,2.0
2,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",1000000.0,2019469.0,96.0,1992-09-16,"(Crime, Drama)",6.417037,6.9,162.0
3,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,0.0,0.0,100.0,2004-01-01,"(Horror, Romance, Comedy)",2.233189,5.0,42.0
4,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,0.0,0.0,80.0,1998-05-27,"(Comedy, Drama, Thriller)",1.800582,6.4,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Basic Instinct 2,Basic Instinct 2,en,Novelist Catherine Tramell is once again in tr...,70000000.0,38629478.0,114.0,2006-03-29,"(Crime, Mystery, Thriller)",15.321902,4.6,183.0
4996,Every Thing Will Be Fine,Every Thing Will Be Fine,en,"One day, driving aimlessly around the outskirt...",0.0,8034.0,118.0,2015-04-02,"(Drama,)",5.723103,5.3,79.0
4997,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,0.0,0.0,95.0,2004-10-28,"(Comedy,)",4.582736,5.2,70.0
4998,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",0.0,0.0,58.0,2000-09-13,"(Drama, TV Movie)",2.364355,8.0,2.0
4999,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",0.0,0.0,90.0,2015-11-24,"(Comedy, Romance)",0.448056,7.0,4.0

Analisando as colunas `budget` e `revenue` percebemos que mais de 70% dos registros possuem valores 0.0 que são `NaN`s disfaçados.

In [2615]:
df_sem_duplicado[df_sem_duplicado['budget'] == 0.0].shape[0]

3900

In [2616]:
df_sem_duplicado[df_sem_duplicado['revenue'] == 0.0].shape[0]

4051

Vamos, então, preencher os dados ausentes e zeros das colunas `budget` e `revenue` com um modelo de regressão de Florestas Aleatórias. Esse modelo performa bem com dados ausentes e outliers, obtendo uma ótima acurácia. Primeiro faremos alguns tratamentos.

Criaremos a coluna `num_genres` com a quantidade de gêneros de cada registro para servir como feature no treinamento da regressão de Florestas Aleatórias. As listas com gêneros não servem como features de um modelo de regressão já que não é um número, logo criaremos a coluna que diz o número de gêneros por filme a fim do modelo de regresão capturar padrões correlacionados a quantidade de gêneros por filme, como, por exemplo, pode prevê que filmes com mais gêneros possuem orçamentos maiores.

In [2617]:
df_sem_duplicado['num_genres'] = df_sem_duplicado['genres'].apply(lambda x: len(x) if isinstance(x, tuple) else 0)

Algumas linhas na coluna `runtime` aparecem com um termo `min` de minutos após o número o que pode causar erro na hora de imputar os valores das colunas. Devemos retiralos.

In [2618]:
df_sem_duplicado['runtime'] = df_sem_duplicado['runtime'].str.replace('min', '', regex=False).str.strip()

Agora trataremos a coluna `release_date` e extrair o ano na nova coluna `release_year` para servir como feature do modelo de regressão de Florestas Aleatórias. Faz sentido usar o ano como feature, pois filmes mais recentes costumam ter orçamentos maiores e ajuda o modelo a entender esses padrões.

In [2619]:
df_sem_duplicado['release_date'] = pd.to_datetime(df_sem_duplicado['release_date'], errors= 'coerce')

In [2620]:
df_sem_duplicado['release_year'] = df_sem_duplicado['release_date'].dt.year

Definindo as features para imputação.

In [2621]:
features_1 = ['runtime', 'popularity', 'vote_average', 'vote_count', 'num_genres', 'release_year']

Definimos a função de imputar coluna.

In [2622]:
def preencher_coluna(df, coluna_alvo, features):
    
    def ausente(x):
        return pd.isna(x) or x == 0
    
    valido = ~df[coluna_alvo].apply(ausente)
    faltante = df[coluna_alvo].apply(ausente)
    
    df_valido = df.loc[valido].dropna(subset=features)
    df_faltante = df.loc[faltante].dropna(subset=features)
    
    if df_valido.empty or df_faltante.empty:
        print(f'{coluna_alvo} não possui dados suficientes para ser preenchida.')
        return df
    
    X_treino = df_valido[features]
    y_treino = df_valido[coluna_alvo]
    X_pred = df_faltante[features]
    
    modelo = RandomForestRegressor(n_estimators=100, random_state=42)
    modelo.fit(X_treino, y_treino)
    
    y_pred = modelo.predict(X_pred)
    
    df.loc[df_faltante.index, coluna_alvo] = y_pred
    
    print('f{coluna_alvo} preenchida com regressão de Frorestas Aleatórias.')
    return df

In [2623]:
df_budget = preencher_coluna(df_sem_duplicado, 'budget', features_1)
df_budget

f{coluna_alvo} preenchida com regressão de Frorestas Aleatórias.

,title,original_title,original_language,overview,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count,num_genres,release_year
0,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",16431284.39,0.0,95.0,2017-04-28,"(Drama, Comedy, Thriller, Crime)",7.219022,5.8,55.0,4,2017.0
1,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",757385.00,0.0,97.0,1972-12-21,"(Drama, Comedy)",0.138450,7.3,2.0,2,1972.0
2,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",1000000.00,2019469.0,96.0,1992-09-16,"(Crime, Drama)",6.417037,6.9,162.0,2,1992.0
3,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,4783182.02,0.0,100.0,2004-01-01,"(Horror, Romance, Comedy)",2.233189,5.0,42.0,3,2004.0
4,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,2344951.39,0.0,80.0,1998-05-27,"(Comedy, Drama, Thriller)",1.800582,6.4,27.0,3,1998.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Basic Instinct 2,Basic Instinct 2,en,Novelist Catherine Tramell is once again in tr...,70000000.00,38629478.0,114.0,2006-03-29,"(Crime, Mystery, Thriller)",15.321902,4.6,183.0,3,2006.0
4996,Every Thing Will Be Fine,Every Thing Will Be Fine,en,"One day, driving aimlessly around the outskirt...",15577293.40,8034.0,118.0,2015-04-02,"(Drama,)",5.723103,5.3,79.0,1,2015.0
4997,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,13210569.59,0.0,95.0,2004-10-28,"(Comedy,)",4.582736,5.2,70.0,1,2004.0
4998,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",3676203.35,0.0,58.0,2000-09-13,"(Drama, TV Movie)",2.364355,8.0,2.0,2,2000.0
4999,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",1064240.43,0.0,90.0,2015-11-24,"(Comedy, Romance)",0.448056,7.0,4.0,2,2015.0

In [2624]:
df_sem_duplicado['budget'].isna().sum()

8

In [2625]:
df_revenue = preencher_coluna(df_sem_duplicado, 'revenue', features_1)
df_revenue

f{coluna_alvo} preenchida com regressão de Frorestas Aleatórias.

,title,original_title,original_language,overview,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count,num_genres,release_year
0,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",16431284.39,5656642.23,95.0,2017-04-28,"(Drama, Comedy, Thriller, Crime)",7.219022,5.8,55.0,4,2017.0
1,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",757385.00,1142617.25,97.0,1972-12-21,"(Drama, Comedy)",0.138450,7.3,2.0,2,1972.0
2,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",1000000.00,2019469.00,96.0,1992-09-16,"(Crime, Drama)",6.417037,6.9,162.0,2,1992.0
3,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,4783182.02,16873001.68,100.0,2004-01-01,"(Horror, Romance, Comedy)",2.233189,5.0,42.0,3,2004.0
4,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,2344951.39,8670258.24,80.0,1998-05-27,"(Comedy, Drama, Thriller)",1.800582,6.4,27.0,3,1998.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Basic Instinct 2,Basic Instinct 2,en,Novelist Catherine Tramell is once again in tr...,70000000.00,38629478.00,114.0,2006-03-29,"(Crime, Mystery, Thriller)",15.321902,4.6,183.0,3,2006.0
4996,Every Thing Will Be Fine,Every Thing Will Be Fine,en,"One day, driving aimlessly around the outskirt...",15577293.40,8034.00,118.0,2015-04-02,"(Drama,)",5.723103,5.3,79.0,1,2015.0
4997,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,13210569.59,15217452.92,95.0,2004-10-28,"(Comedy,)",4.582736,5.2,70.0,1,2004.0
4998,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",3676203.35,22734909.65,58.0,2000-09-13,"(Drama, TV Movie)",2.364355,8.0,2.0,2,2000.0
4999,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",1064240.43,1428111.07,90.0,2015-11-24,"(Comedy, Romance)",0.448056,7.0,4.0,2,2015.0

In [2626]:
df_sem_duplicado['revenue'].isna().sum()

5

Mudando o tipo da coluna `runtime` para `float`.

In [2627]:
df_sem_duplicado['runtime'] = df_sem_duplicado['runtime'].astype(float)

In [2628]:
df_sem_duplicado.isnull().sum()

title                  1
original_title         0
original_language      1
overview              98
budget                 8
revenue                5
runtime              127
release_date         115
genres                 0
popularity             1
vote_average           1
vote_count             1
num_genres             0
release_year         115
dtype: int64

Agora vamos preencher os valores `NaN` da coluna `runtime` usando como features as colunas em `features_2`.

In [2629]:
features_2 = ['popularity', 'vote_average', 'vote_count', 'num_genres', 'release_year']

In [2630]:
df_runtime = preencher_coluna(df_sem_duplicado, 'runtime', features_2)
df_runtime

f{coluna_alvo} preenchida com regressão de Frorestas Aleatórias.

,title,original_title,original_language,overview,budget,revenue,runtime,release_date,genres,popularity,vote_average,vote_count,num_genres,release_year
0,Small Crimes,Small Crimes,en,"A disgraced former cop, fresh off a six-year p...",16431284.39,5656642.23,95.0,2017-04-28,"(Drama, Comedy, Thriller, Crime)",7.219022,5.8,55.0,4,2017.0
1,Up the Sandbox,Up the Sandbox,en,"A young wife and mother, bored with day-to-day...",757385.00,1142617.25,97.0,1972-12-21,"(Drama, Comedy)",0.138450,7.3,2.0,2,1972.0
2,Bad Lieutenant,Bad Lieutenant,en,"While investigating a young nun's rape, a corr...",1000000.00,2019469.00,96.0,1992-09-16,"(Crime, Drama)",6.417037,6.9,162.0,2,1992.0
3,Satan's Little Helper,Satan's Little Helper,en,A naïve young boy unknowingly becomes the pawn...,4783182.02,16873001.68,100.0,2004-01-01,"(Horror, Romance, Comedy)",2.233189,5.0,42.0,3,2004.0
4,Sitcom,Sitcom,fr,The adventures of an upper-class suburban fami...,2344951.39,8670258.24,80.0,1998-05-27,"(Comedy, Drama, Thriller)",1.800582,6.4,27.0,3,1998.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Basic Instinct 2,Basic Instinct 2,en,Novelist Catherine Tramell is once again in tr...,70000000.00,38629478.00,114.0,2006-03-29,"(Crime, Mystery, Thriller)",15.321902,4.6,183.0,3,2006.0
4996,Every Thing Will Be Fine,Every Thing Will Be Fine,en,"One day, driving aimlessly around the outskirt...",15577293.40,8034.00,118.0,2015-04-02,"(Drama,)",5.723103,5.3,79.0,1,2015.0
4997,Seven Dwarfs,7 Zwerge - Männer allein im Wald,de,The Seven Dwarves live deep within a female-fr...,13210569.59,15217452.92,95.0,2004-10-28,"(Comedy,)",4.582736,5.2,70.0,1,2004.0
4998,True Siblings,Syskonsalt,sv,"The siblings Linus, 19-years-old, who are taki...",3676203.35,22734909.65,58.0,2000-09-13,"(Drama, TV Movie)",2.364355,8.0,2.0,2,2000.0
4999,Paternity Leave,Paternity Leave,en,"Four years into his first stable relationship,...",1064240.43,1428111.07,90.0,2015-11-24,"(Comedy, Romance)",0.448056,7.0,4.0,2,2015.0

In [2631]:
df_runtime.isnull().sum()

title                  1
original_title         0
original_language      1
overview              98
budget                 8
revenue                5
runtime                5
release_date         115
genres                 0
popularity             1
vote_average           1
vote_count             1
num_genres             0
release_year         115
dtype: int64

Os valores na coluna `overview` são únicos e com poucos `NaN`s, apenas retiraremos essas linhas do DF, pois não conseguimos inferir valores para eles. Além disso, faremos o mesmo com as demais colunas que ainda possuem `NaN` e no final teremos apenas eliminado pouco mais de 200 registros do DF, o que não afetará muito no modelo de `Machine Learning`.

In [2632]:
df_runtime = df_runtime.dropna(subset=['overview'])
df_runtime = df_runtime.dropna(subset=['release_date'])
df_runtime = df_runtime.dropna(subset=['original_language'])
df_runtime = df_runtime.dropna(subset=['budget'])

In [2633]:
df_runtime.isnull().sum()

title                0
original_title       0
original_language    0
overview             0
budget               0
revenue              0
runtime              0
release_date         0
genres               0
popularity           0
vote_average         0
vote_count           0
num_genres           0
release_year         0
dtype: int64

Mudando o tipo da coluna `original_language`.

In [2634]:
df_runtime['original_language'] = df_runtime['original_language'].astype('category')

Agora todas as colunas estão com os tipo corretos.

In [2635]:
df_filmes_limpos = df_runtime.reset_index(drop=True)
df_filmes_limpos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4788 entries, 0 to 4787
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              4788 non-null   object
 1   original_title     4788 non-null   object
 2   original_language  4788 non-null   category
 3   overview           4788 non-null   object
 4   budget             4788 non-null   float64
 5   revenue            4788 non-null   float64
 6   runtime            4788 non-null   float64
 7   release_date       4788 non-null   datetime64[ns]
 8   genres             4788 non-null   object
 9   popularity         4788 non-null   float64
 10  vote_average       4788 non-null   float64
 11  vote_count         4788 non-null   float64
 12  num_genres         4788 non-null   int64
 13  release_year       4788 non-null   float64
dtypes: category(1), datetime64[ns](1), float64(7), int64(1), object(4)
memory usage: 493.6+ KB

## Salvando o dataframe

In [2636]:
df_filmes_limpos.to_csv('../data/processed/filmes_limpos.csv', index=False)